name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.67.2
      - uses: taiga-family/ci/actions/setup/node@v1.67.2
      - run: |
          npm run prettier -- --check
          npm run lint
          npm run build
          npm test

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
