name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.55.13
      - uses: taiga-family/ci/actions/setup/node@v1.55.13
      - run: npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.55.13
      - uses: taiga-family/ci/actions/setup/node@v1.55.13
      - run: npm run prettier -- --check
      - run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.55.13
      - uses: taiga-family/ci/actions/setup/node@v1.55.13
      - run: npm test

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
