name: Deploy demo to gh-pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.60.1
      - uses: taiga-family/ci/actions/setup/variables@v1.60.1
      - run: npm run build:demo
      - uses: taiga-family/ci/actions/deploy/github-pages@v1.60.1
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/apps/demo
