name: Deploy demo
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: taiga-family/ci/actions/setup/variables@v1.86.0
      - uses: taiga-family/ci/actions/setup/node@v1.86.0
      - run: npm run build:demo
      - uses: taiga-family/ci/actions/deploy/github-pages@v1.86.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/apps/demo
