name: Release Workflow

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

on:
  push:
    branches:
      - main
      - beta
      - alpha

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: taiga-family/ci/actions/setup/node@v1.44.5
      - uses: taiga-family/ci/actions/setup/config/npm@v1.44.5
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: release
        run: npm run release
        env:
          CI: true
          GH_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
